### ISSUE TITLE
Tuples and Records page is confusing in regards to 0/1 indexing

### ISSUE THREAD

**Issue by spreadLink** [diku-dk/futhark-website#23]
Hey, I'm going through the Futhark Examples pages, and the one titled "tuples-and-records.fut" is giving conflicting information as to if tuples are 0 or 1 indexed. I remember from the design-mistakes blogpost that tuples at least _used_ to be 1-indexed, but the page claims this is just like arrays (who are actually 0 indexed), and all examples that use projections show indexing by 0.  

I'd submit a PR for it, but I'm unfortunately not sure which one is actually the way it is done now.

**Comment by athas** [comment]
Everything is 0-indexed now.

**Comment by spreadLink** [comment]
Okay, is it worth making a PR for it?

**Comment by athas** [comment]
Yes please!  You're apparently better at spotting these than I am.

**Comment by spreadLink** [comment]
Done  #24
