### ISSUE TITLE
IPv6 doesn't work

### ISSUE THREAD

**Issue by tambry** [diku-dk/futhark-website#6]
While there's an AAAA record for the website, connecting to the given IPv6 address just times out.  
This is likely due to firewall blocking IPv6 connections.

**Comment by Athas** [comment]
Curious - I could have sworn it used to work.  I can't even ping6 futhark-lang.org right now.

**Comment by Athas** [comment]
Does it work now?  (I don't have IPv6 at home, but I can ping6 and telnet it from other servers.)

**Comment by tambry** [comment]
I can confirm it works now. Thanks for fixing this!
