### ISSUE TITLE
pyopencl + Mandelbrot blog post out of date

### ISSUE THREAD

**Issue by albertgoncalves** [diku-dk/futhark-website#9]
In my adventures getting started with Futhark I came across [this early-days blog](https://futhark-lang.org/blog/2016-04-15-futhark-and-pyopencl.html) post. Seeking to replicate the Mandelbrot example was trickier than I expected due to changes in the language rendering the displayed source code unusable without modification.

I was able to get it working, and have a [minimal repo](https://github.com/albertgoncalves/hello_futhark/blob/master/src/mandelbrot.fut) setup with the revised code. If there is any appetite for updating this post, I would be interested in lending a hand to do so. It was extremely satisfying to render the Mandelbrot set as a newcomer to Futhark; it would be great to ease this difficulty for future new users down the line.

**Comment by athas** [comment]
Sure, I agree.  Feel free to send a pull request; otherwise I'll probably update it myself tomorrow.

**Comment by athas** [comment]
Closed in #10.
